[general]
static=yes
writeprotect=no
autofallthrough=yes

[default]
exten => 9196,1,NoOp(echo test from ${CALLERID(num)})
 same => n,Answer()
 same => n,Wait(1)
 same => n,Playback(demo-echotest)
 same => n,Echo()
 same => n,Hangup()

exten => _X.,1,NoOp(call to ${EXTEN} from ${CALLERID(num)})
 same => n,Hangup()
