[general]
static=yes
writeprotect=no
autofallthrough=yes

[from-kamailio]
exten => 9196,1,NoOp(echo test from ${CALLERID(num)})
 same => n,Answer()
 same => n,Wait(1)
 same => n,Echo()
 same => n,Hangup()

exten => _X.,1,NoOp(outbound ${EXTEN} from ${CALLERID(num)})
 same => n,Dial(PJSIP/${EXTEN}@trunk,30,gT)
 same => n,Hangup()

[from-trunk]
exten => _X.,1,NoOp(inbound DID ${EXTEN} from trunk)
 same => n,Hangup()
